#!/bin/bash

set -e

BUILD_DIR=$1
CACHE_DIR=$2
ENV_DIR=$3
DOWNLOAD_URI=$(cat ${ENV_DIR}/MATTERMOST_DOWNLOAD_URI)

# add begin
set -x
echo $(pwd)
pushd ${BUILD_DIR}
echo $(pwd)
curl -sS --create-dirs -o heroku/heroku.tar.xz $(curl -sS https://cli-assets.heroku.com/linux-x64 | grep -oE https.+xz)

pushd heroku
tar xf heroku.tar.xz --strip-components=1
rm heroku.tar.xz
./bin/heroku plugins --core
./bin/heroku update &
rm heroku.tar.xz
popd
popd
# add end

echo "-----> Retrieving mattermost tar from ${DOWNLOAD_URI}" 
curl -s -L "${DOWNLOAD_URI}" | tar -zxf - --strip-components=1 -C ${BUILD_DIR}
mkdir data/
